name: warden
on:
  push:
    branches: [main, develop, feature/*, refactor/*, bugfix/*, hotfix/*]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make release
        run: make release
      - name: warden version
        run: ./warden --version
      - name: warden init
        run: ./warden --init
      - name: warden seed
        run: ./warden --seed
      - name: warden start
        run: |
          address=0.0.0.0
          port=2254
          ./warden --address $address --port $port >warden.log 2>&1 &
          for i in {1..8}; do
            if nc -z $address $port; then
              echo "listening on $address $port"
              break
            fi
            echo "waiting for listening socket"
            sleep 1
          done
          if ! nc -z $address $port; then
            echo "$address $port timed out"
            exit 1
          fi
